### PR TITLE
+ The Event Chain Supports   + the event object as listener's "this" object.   + return the result property of event object to emitter object.   + prevent the rest of listener from be excuted if set the stopped property of event object to true

### PR DESCRIPTION
**Pull request by snowyu**
+ The Event Chain Supports 
  + the event object as listener's "this" object. 
  + return the result property of event object to emitter object. 
  + prevent the rest of listener from be excuted if set the stopped property of event object to true

### CODE REVIEW

**Comment by medikoo** [comment]
Thanks @snowyu but _event-emitter_ is quite low-level, and it's used in some very hot paths. Adding such custom functionalities (which in most cases won't be used) adds unnecesary complexity and affects performance.

All of this can be achieved outside, with some custom extensions, or special handling of event objects to which this engine is agnostic.

**Comment by snowyu** [comment]
You are right. let me think a little.

**Comment by snowyu** [comment]
It can be a extensions if do not need stop the left listeners to be executed.

**Comment by snowyu** [comment]
It's too ugly: 

```js
module.exports = function (emit) {
  function Event(target) {
    this.target   = target;
    this.stopped  = false;
    this.result   = undefined;
  }
  return function(type) {
    var evt = new Event();
    this.__evt__ = evt;
    emit.apply(this, arguments);
    return evt.result;
  }
}
```

**Pull request closed without merging**
